### PR TITLE
Connect-button script manual

### PR DESCRIPTION
**Pull request by dkgitdev**
Hey!

I've been struggling through re-connection issues on windows 10 and found this brilliant project!
It allowed me to make convenient scripts to reconnect to my game controllers.

So I've written a small manual for my situation. I know a lot of people suffer from these issues as well (on [windows forums](https://answers.microsoft.com/en-us/windows/forum/all/is-there-any-way-to-reconnect-a-bluetooth/c8aedd0b-6817-42a5-899e-8047b4f1343b), [superuser](https://superuser.com/questions/1808140/how-to-reconnect-already-paired-bluetooth-controller) and [reddit](https://www.reddit.com/r/WindowsHelp/comments/10clita/repair_bluetooth_controller_without_removing/) to name a few).

### CODE REVIEW

**Comment by PolarGoose** [comment]
Hello @dkgitdev,
Thank you very much for your contribution.
It is a very good idea to add some useful scripts examples.
I myself use the following script to pair my Bluetooth mouse:
```
C:\my\Programms\BluetoothDevicePairing.exe unpair-by-name --name "MX Ergo" --type BluetoothLE --discovery-time 1
C:\my\Programms\BluetoothDevicePairing.exe pair-by-name --name "MX Ergo" --type BluetoothLE --discovery-time 10
if %ErrorLevel% NEQ 0 (
    pause
    exit /b %errorlevel%
)
```

Give me some time to process your pull request. I will try to do it during the upcoming weekend.

**Comment by dkgitdev** [comment]
Hi @PolarGoose, pleased to meet you.

Sure, no rush intended :)

**Comment by PolarGoose** [comment]
@dkgitdev,
I have added the script example in the Readme.
What do you think? Is it enough?

**Comment by dkgitdev** [comment]
Thanks! Looks good!

**Comment by dkgitdev** [comment]
Thanks for your work!

You can close this PR whenever you like ;)

**Comment by PolarGoose** [comment]
@dkgitdev,
Thank you for your work as well.

**Pull request closed without merging**
